# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4FXH_RHDfmlhoCpQmDvDaQ6lWgdrpU-
"""

# app.py (Streamlit version)
import streamlit as st
import pandas as pd
from joblib import load

st.title("Heart Attack Risk Predictor")

# Load your pipeline
model = load("heart_lr_pipeline.joblib")

# Build inputs
inputs = {}
for col in model.named_steps['preprocessor'].feature_names_in_:
    inputs[col] = st.text_input(col)

if st.button("Predict"):
    df = pd.DataFrame([inputs])
    df = df.astype(model.named_steps['preprocessor'].dtype_)  # cast types
    pred = model.predict(df)[0]
    proba = model.predict_proba(df)[0,1]
    st.write(f"**Prediction:** {'Yes' if pred else 'No'}")
    st.write(f"**Probability:** {proba:.2%}")