# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4FXH_RHDfmlhoCpQmDvDaQ6lWgdrpU-
"""

# app.py
from fastapi import FastAPI
from pydantic import BaseModel
import pandas as pd
from joblib import load

app = FastAPI()
model = load("heart_lr_pipeline.joblib")

class HeartData(BaseModel):
    Age: float
    Sex: str
    ChestPainType: str
    RestingBP: float
    Cholesterol: float
    FastingBS: float
    RestingECG: str
    MaxHR: float
    ExerciseAngina: str
    Oldpeak: float
    ST_Slope: str

@app.post("/predict")
def predict(data: HeartData):
    df = pd.DataFrame([data.dict()])
    pred = model.predict(df)[0]
    prob = model.predict_proba(df)[0,1]
    return {"had_heart_attack": int(pred), "probability": float(prob)}